### ISSUE TITLE
[Bug] QuestionnaireResponse search: Questionnaire query parameter results in empty searchset

### ISSUE THREAD

**Issue by christopher-watanabe-snkeos** [awslabs/fhir-works-on-aws-search-es#196] opened 2023-03-23 11:15 UTC
**Describe the bug**
I would like to query QuestionnaireResponses based on the value of the ["questionnaire" field](https://www.hl7.org/fhir/questionnaireresponse-definitions.html#QuestionnaireResponse.questionnaire), where the value of the questionnaire field points to a url like `https://my.questionnaires.com/questionnaire:qr_type:1.0.0`.

The goal is to get a list of QuestionnaireResponses for a specific Questionnaire.

My request looks like this: 

`GET {{FHIR_API_URL}}/fhir/{{TENANT_ID}}/QuestionnaireResponse?questionnaire=https://my.questionnaires.com/questionnaire:qr_type:1.0.0`

where {{FHIR_API_URL}}/fhir points to my AWS fhir works instance. 

This query results in an empty searchset, even when I URL encode the request.

**To Reproduce**
1. Have a running fhir works instance.
2. Upload test QuestionnaireResponse with some specific value for the questionnaire. 
3. Make GET request for QuestionnaireResponses referencing specific questionnaire value.

**Expected behavior**
All QuestionnaireResponses of specific Questionnaire value are returned. 

**Screenshots**
POST QuestionnaireResponse with questionnaire = `https://my.questionnaires.com/questionnaire:qr_type:1.0.0`. Status 201 Created.
![image](https://user-images.githubusercontent.com/91735518/227185400-5625f381-4c7a-4093-ba56-d344a2d8c9ea.png)

Query of QuestionnaireResponse with questionnaire value `https://my.questionnaires.com/questionnaire:qr_type:1.0.0` results in empty searchset. Status 200 OK.
![image](https://user-images.githubusercontent.com/91735518/227186262-b6d6d90c-b75f-4f72-b9fe-ae2a85fa041f.png)

**Versions (please complete the following information):**
 - Release Version installed: v3.12.0

**Additional context**

**Comment by nguyen102** [comment] 2023-03-23 15:33
Duplicate of this ticket
https://github.com/awslabs/fhir-works-on-aws-deployment/issues/826

**Closed as completed by nguyen102** 2023-03-23 15:33 UTC
Labels: bug, duplicate, Review One, Review Two
