### ISSUE TITLE
[Bug] Paged results not returning the same result set

### ISSUE THREAD

**Issue by ghost** [awslabs/fhir-works-on-aws-search-es#128] opened 2021-10-21 19:18 UTC
**Describe the bug**
When a request results in paging, if you run the same request multiple times the results returned in the set are not always the same.

**To Reproduce**
1. Call request something like {{API_URL}}/tenant/7db7dfb5-2f73-4b96-bcf1-131410518850/Observation?patient=Patient/8743177f-ad8b-4dba-b05d-933419da86df&category=vital-signs&_getpagesoffset=0&_count=20
In our case it was returning 20 of 47.

**Expected behavior**
Results returned should be the same when making the same call.

**Additional context**
If we add a _sort=date or _sort=_lastUpdated to our request does seem to resolve the issue.I have also attached the results of both runs
[Run1.txt](https://github.com/awslabs/fhir-works-on-aws-search-es/files/7392312/Run1.txt)
.
[Run2.txt](https://github.com/awslabs/fhir-works-on-aws-search-es/files/7392314/Run2.txt)

**Comment by carvantes** [comment] 2021-10-28 19:47
Hi, 

The issue has been fixed by the 3 PRs that are mentioned above. To get the fix you need to update to: 

- fhir-works-on-aws-interface@11.3.0
- fhir-works-on-aws-search-es@3.7.0
- fhir-works-on-aws-routing@6.3.0

At the time of writing this they the latest versions of those packages.

Please try it out. Feel free to reopen this issue if the issue persists.

---

The root cause was something often referred to as the "bouncing results" issue. 
> Imagine that you are sorting your results by a timestamp field, and two documents have the same timestamp. Because search requests are round-robined between all available shard copies, these two documents may be returned in one order when the request is served by the primary, and in another order when served by the replica.
> 
> This is known as the bouncing results problem: every time the user refreshes the page, the results appear in a different order. The problem can be avoided by always using the same shards for the same user, which can be done by setting the preference parameter to an arbitrary string like the user’s session ID.

The fix is to use a `sessionId` as the [Elasticsearch preference parameter](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-search.html#search-preference). The chosen `sessionId` is a hash of the JWT token claims.

- https://www.elastic.co/guide/en/elasticsearch/guide/current/_search_options.html#_preferencehttps://www.elastic.co/guide/en/elasticsearch/reference/current/search-shard-routing.html#shard-and-node-preference
- https://www.elastic.co/guide/en/elasticsearch/guide/current/_search_options.html#_preference

**Closed as completed by carvantes** 2021-10-28 19:47 UTC
Labels: bug
